/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.maxkorte;

public class GGT {
    public static void main(String[] args) {
        try{
            System.out.println(getGGT(Integer.parseInt(args[0]), Integer.parseInt(args[1])));
        } catch(Exception e){
            System.out.println("fehlerhafte Eingabe!");
        }
    }

    public static int getGGT(int a, int b){
        if (a == 0) return b;
        while (b != 0){
            if (a > b) a -= b;
            else b -= a;
        }
        return a;
    }
}
