/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.maxkorte;

public class GGT {
    public static void main(String[] args) {
        try {
            System.out.println(getGGT(Integer.parseInt(args[0]), Integer.parseInt(args[1])));
        } catch (ArrayIndexOutOfBoundsException e){
            System.out.println("Es müssen 2 Parameter angegeben werden!");
        }
        catch (NumberFormatException e){
            System.out.println("fehlerhafte Eingabe!");
        } catch (IllegalArgumentException e){
            e.printStackTrace();
        }

    }

    public static int getGGT(int a, int b) {
        if (a == 0 && b == 0) throw new IllegalArgumentException("Nur eine der beiden Zahlen darf 0 sein!");
        if (a < 0 || b < 0) throw new IllegalArgumentException("Die Zahlen dürfen nicht kleiner als 0 sein!");

        if (a == 0) return b;
        while (b != 0){
            if (a > b) a -= b;
            else b -= a;
        }
        return a;
    }
}
