/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.maxkorte.GGT;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test
    public void testGetGGT() {
        assertEquals(5, App.getGGT(0, 5));
        assertEquals(7, App.getGGT(7, 0));
        assertEquals(25, App.getGGT(25, 50));
        assertEquals(3, App.getGGT(9, 6));
        assertEquals(27, App.getGGT(27, 27));
    }
}
